### PR TITLE
New Apple push production certificate format.

### PR DESCRIPTION
**Pull request by v-tsymbalistyi**
Fix regarding issue #585.

### CODE REVIEW

**Comment by leopoldovilla** [comment]
You need change DetectProduction too.

if (subjectName.Contains("Apple Production IOS Push Services") || subjectName.Contains("Apple Push Services"))
					production = true;

**Comment by Redth** [comment]
Can anyone actually confirm the single cert works with the old binary APNS protocol too?  To me it looks like this is only for the new HTTP/2 provider API.

**Comment by v-tsymbalistyi** [comment]
Tested it twice.
With disabled certificate check and no other changes push was delivered.
With posted change also worked as expected.

**Comment by v-tsymbalistyi** [comment]
leopoldovilla, good suggestion.

**Comment by tisganitis** [comment]
@Redth I just tested and can also confirm that these new SSL certificates do work with the old binary APNS protocol. (They also work, as Apple promised, with both production and sandbox push gateways.) So, using one of these certs should not break anything for an existing app using the binary protocol.

**Comment by Redth** [comment]
Thanks!  I think I'll remove the cert checks entirely and simplify the constructors going forward rather than merge this, so it's less confusing to use.

**Comment by AdamLiechty** [comment]
:+1: Thanks @Redth !

**Comment by kydlo** [comment]
Thank you as well @Redth

**Comment by harshadcs** [comment]
Can you please confirm that Push Notification is working after P12 policy updated by iOS?
We changed our code as per your new code, we are not getting any exception, but we are also not getting Notification

**Comment by perlasivakrishna** [comment]
I am not able to change to disableCertificateCheck=true in .cs class. i am getting this from pushsharp.apple.dll file ( public ApplePushChannelSettings(bool production, byte[] certificateData, string certificateFilePwd, bool disableCertificateCheck = false);),
as per your recent change we need to remove disableCertificateCheck. but i am not able to remove. can you please provide me new pushsharp.apple.dll file.
Thanks in advance.

**Comment by Redth** [comment]
I won't be updating the 2.x version with changes, but the 3.0-dev branch already contains these changes.  If you want to keep using 2.x, you can just use the constructor for `ApplePushChannelSettings` that allows you to se the `production` and `disableCertificateCheck` flags accordingly, no need to recompile to work around this.

**Pull request closed without merging**
