### PR TITLE
Added support for higher TLS versions

### PR DESCRIPTION
**Pull request by narensoni83**
Added support for higher TLS version. 
Currently pushsharp only work on TLS1.0. Added a fix to support TLS1.1 and TLS1.2

### CODE REVIEW

**Comment by SamuelFrankSmith** [comment]
Could redth consider this PR for merge? Thank you.

**Comment by PavelEmelyanov** [comment]
Waiting for merge!

**Comment by martinmalyakov** [comment]
Any progress on this one?

**Comment by snoopydo** [comment]
According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.7.2) you should be specifying `SslProtocols.None`, this lets the OS negotiate the best protocol.

**Pull request merged**
