### PR TITLE
Migrated to .NET 5

### PR DESCRIPTION
**Pull request by RosenDev**
PR created by issue #933

### CODE REVIEW

**Comment by RosenDev** [comment]
You have to change the CI in order to build this project

**Comment by tomkocyan** [comment]
What is an actual state of this migration? Does it work on .NET6?

**Comment by RosenDev** [comment]
> What is an actual state of this migration? Does it work on .NET6?

At the time when I created it .NET 6 was not fully completed it was still beta. So yes now it is no longer relevant. If you haven't migrated to .NET 6 I can do a new PR for it

**Comment by tomkocyan** [comment]
Oh yes, please!

**Pull request closed without merging**
