### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dylanvdmerwe**
Fixes to the code examples.

### CODE REVIEW

**Comment by dylanvdmerwe** [comment]
In reference to https://github.com/Redth/PushSharp/issues/660

**Comment by Redth** [comment]
@dylanvdmerwe thanks, this is much appreciated, but could you please change the references to the mispelled `DeviceSubscriptonExpired` class *back* to `DeviceSubscriptionExpired` ? I've added a class which fixes this in e56b7b6d99b79014e6bab77e389e024b9395e3d7.  It does keep the old class around (and for now, subclasses it) just to not break existing code, but I'd like users to use the correct version going forward as you and others have identified the typo :)

**Comment by dylanvdmerwe** [comment]
Done :+1:

**Comment by Redth** [comment]
Thanks so much!

**Pull request merged**
